[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[dev]
  command = "vite"
  targetPort = 5173
  framework = "#custom"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@anthropic-ai/sdk", "@supabase/supabase-js"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
