[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://members.theinterviewguys.com"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Access-Control-Allow-Origin = "https://members.theinterviewguys.com"
    Content-Type = "application/javascript"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Access-Control-Allow-Origin = "https://members.theinterviewguys.com"
    Content-Type = "text/css"
